apiVersion: v2
description: A Helm chart for Open Service Broker For Azure
name: open-service-broker-azure
version: 0.0.1
appVersion: 0.0.1
keywords:
  - azure
  - services
  - service broker
home: https://github.com/adobe-platform/open-service-broker-azure
sources:
  - https://github.com/adobe-platform/open-service-broker-azure
  - https://hub.docker.com/r/microsoft/azure-service-broker/
maintainers:
  - name: Kent Rancourt
    email: kent.rancourt@microsoft.com
  - name: Jeremy Rickard
    email: jeremy.rickard@microsoft.com
dependencies:
  - name: redis
    version: 10.3.4
    condition: redis.embedded
    repository: https://kubernetes-charts.storage.googleapis.com/